# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI
on:
  push:
  pull_request:
    branches: [master]

jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r {{cookiecutter.project_slug}}/requirements-dev.txt

      {%- if cookiecutter.use_pylint == "y" %}
      - name: Analysing the code with pylint
        run: |
          pylint -v --rcfile={{cookiecutter.project_slug}}/.pylintrc {{cookiecutter.project_slug}}/*.py
      {%- endif %}

      {%- if cookiecutter.use_pytest == "y" %}
      - name: Analysing the code with pytest
        run: |
          pytest -vv {{cookiecutter.project_slug}}
      {%- endif %}
