version: 2
updates:
  - package-ecosystem: pip
    directory: "{{cookiecutter.project_slug}}/"
    schedule:
      interval: weekly
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "feat"
      include: "scope"
